set_property PACKAGE_PIN B6 [get_ports clk_1k]
set_property IOSTANDARD LVCMOS33 [get_ports clk_1k]

set_property PACKAGE_PIN Y1 [get_ports clr_sw_n]
set_property IOSTANDARD LVCMOS33 [get_ports clr_sw_n]

set_property PACKAGE_PIN W3 [get_ports alarm_sw]
set_property IOSTANDARD LVCMOS33 [get_ports alarm_sw]

set_property PACKAGE_PIN U2 [get_ports stopwatch_sw]
set_property IOSTANDARD LVCMOS33 [get_ports stopwatch_sw]

set_property PACKAGE_PIN T1 [get_ports timer_sw]
set_property IOSTANDARD LVCMOS33 [get_ports timer_sw]

set_property IOSTANDARD LVCMOS33 [get_ports {btn[*]}]
set_property PACKAGE_PIN K4 [get_ports {btn[0]}]
set_property PACKAGE_PIN N8 [get_ports {btn[1]}]
set_property PACKAGE_PIN N4 [get_ports {btn[2]}]
set_property PACKAGE_PIN N1 [get_ports {btn[3]}]
set_property PACKAGE_PIN P6 [get_ports {btn[4]}]
set_property PACKAGE_PIN N6 [get_ports {btn[5]}]
set_property PACKAGE_PIN L5 [get_ports {btn[6]}]
set_property PACKAGE_PIN J2 [get_ports {btn[7]}]
set_property PACKAGE_PIN K2 [get_ports {btn[8]}]

set_property PACKAGE_PIN A6 [get_ports lcd_e]
set_property PACKAGE_PIN G6 [get_ports lcd_rs]
set_property PACKAGE_PIN D6 [get_ports lcd_rw]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_e]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_rs]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_rw]

set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[*]}]
set_property PACKAGE_PIN A4 [get_ports {lcd_data[0]}]
set_property PACKAGE_PIN B2 [get_ports {lcd_data[1]}]
set_property PACKAGE_PIN C3 [get_ports {lcd_data[2]}]
set_property PACKAGE_PIN D4 [get_ports {lcd_data[3]}]
set_property PACKAGE_PIN A2 [get_ports {lcd_data[4]}]
set_property PACKAGE_PIN C5 [get_ports {lcd_data[5]}]
set_property PACKAGE_PIN C1 [get_ports {lcd_data[6]}]
set_property PACKAGE_PIN D1 [get_ports {lcd_data[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[*]}]
set_property PACKAGE_PIN K1 [get_ports {seg_sel[0]}]
set_property PACKAGE_PIN L6 [get_ports {seg_sel[1]}]
set_property PACKAGE_PIN G3 [get_ports {seg_sel[2]}]
set_property PACKAGE_PIN G1 [get_ports {seg_sel[3]}]
set_property PACKAGE_PIN H6 [get_ports {seg_sel[4]}]
set_property PACKAGE_PIN H4 [get_ports {seg_sel[5]}]
set_property PACKAGE_PIN K3 [get_ports {seg_sel[6]}]
set_property PACKAGE_PIN K5 [get_ports {seg_sel[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[*]}]
set_property PACKAGE_PIN F1 [get_ports {seg_data[0]}]
set_property PACKAGE_PIN F5 [get_ports {seg_data[1]}]
set_property PACKAGE_PIN E2 [get_ports {seg_data[2]}]
set_property PACKAGE_PIN E4 [get_ports {seg_data[3]}]
set_property PACKAGE_PIN J1 [get_ports {seg_data[4]}]
set_property PACKAGE_PIN J3 [get_ports {seg_data[5]}]
set_property PACKAGE_PIN J7 [get_ports {seg_data[6]}]
set_property PACKAGE_PIN H2 [get_ports {seg_data[7]}]

set_property PACKAGE_PIN Y21 [get_ports piezo]
set_property IOSTANDARD LVCMOS33 [get_ports piezo]

set_property IOSTANDARD LVCMOS33 [get_ports {led_1[*]}]
set_property PACKAGE_PIN L4 [get_ports {led_1[0]}]
set_property PACKAGE_PIN M4 [get_ports {led_1[1]}]
set_property PACKAGE_PIN M2 [get_ports {led_1[2]}]
set_property PACKAGE_PIN N7 [get_ports {led_1[3]}]
set_property PACKAGE_PIN M7 [get_ports {led_1[4]}]
set_property PACKAGE_PIN M3 [get_ports {led_1[5]}]
set_property PACKAGE_PIN M1 [get_ports {led_1[6]}]
set_property PACKAGE_PIN N5 [get_ports {led_1[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {led_r[*]}]
set_property PACKAGE_PIN T2 [get_ports {led_r[0]}]
set_property PACKAGE_PIN U1 [get_ports {led_r[1]}]
set_property PACKAGE_PIN P2 [get_ports {led_r[2]}]
set_property PACKAGE_PIN R3 [get_ports {led_r[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {led_g[*]}]
set_property PACKAGE_PIN U5 [get_ports {led_g[0]}]
set_property PACKAGE_PIN V1 [get_ports {led_g[1]}]
set_property PACKAGE_PIN R7 [get_ports {led_g[2]}]
set_property PACKAGE_PIN T6 [get_ports {led_g[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {led_b[*]}]
set_property PACKAGE_PIN U3 [get_ports {led_b[0]}]
set_property PACKAGE_PIN W2 [get_ports {led_b[1]}]
set_property PACKAGE_PIN R5 [get_ports {led_b[2]}]

set_property PACKAGE_PIN T3 [get_ports {led_b[3]}]
